sonar.projectKey=proops2026-taskmanager_user-service
sonar.organization=proops2026-taskmanager

sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/__tests__/**/*.test.ts
sonar.exclusions=**/node_modules/**,**/dist/**,**/__tests__/**

sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.typescript.lcov.reportPaths=coverage/lcov.info
